### GENERAL SETTINGS ###

# Site settings
title: Jamie Hogg
description: "Games development Portfolio."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "https://JamieHogg.github.io/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#4169E1" #"#F70031"
  primary_rgb: "65,105,225" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jamiehogg/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Gillingham, Dorset, United Kingdom
email: 



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Jamie Hogg
    position: Graduate Game Developer.
    text: I am a keen and passionate games developer, whose love of programming extends to mentoring others to allow them to develop games for themselves.
    img: profile_01.png
    social:
      - title: envelope #use for email address
        url: mailto:
      - title: twitter
        url: 
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Graduate Game Developer."
